### ISSUE TITLE
NPE in ProjectDirectories#fromPath on Windows 8.1

### ISSUE THREAD

**Issue by smarter** [soc/directories-jvm#17]
Hi,

I can't reproduce it myself since I don't have that OS but it seems that ProjectDirectories#fromPath does not always work on Windows 8.1 (background: the Functional Programming class at EPFL has assignments that use scalafix for linting, scalafix uses coursier, coursier uses directories), here's the stack trace from one student:
```java
 [error] java.lang.NullPointerException
[error]         at com.geirsson.shaded.directories.ProjectDirectories.fromPath(ProjectDirectories.java:221)
[error]         at com.geirsson.shaded.directories.ProjectDirectories.from(ProjectDirectories.java:272)
[error]         at com.geirsson.shaded.coursier.CoursierPaths.cacheDirectory(CoursierPaths.java:61)
[error]         at com.geirsson.shaded.coursier.CachePath.defaultCacheDirectory(CachePath.java:88)
[error]         at com.geirsson.shaded.coursier.Cache$.default$lzycompute(Cache.scala:1131)
[error]         at com.geirsson.shaded.coursier.Cache$.default(Cache.scala:1131)
    [error]         at com.geirsson.shaded.coursier.Cache$.fetch$default$1(Cache.scala:1023)
[error]         at com.geirsson.coursiersmall.CoursierSmall$.fetch(CoursierSmall.scala:39)
    [error]         at scalafix.internal.sbt.ScalafixCoursier$.scalafixCliJars(ScalafixCoursier.scala:22)
[error]         at scalafix.internal.sbt.ScalafixInterface$.$anonfun$fromToolClasspath$1(ScalafixInterface.scala:20)
[error]         at scala.util.Try$.apply(Try.scala:209)
    [error]         at scalafix.internal.sbt.ScalafixInterface$LazyValue._value$lzycompute(ScalafixInterface.scala:12)
    [error]         at scalafix.internal.sbt.ScalafixInterface$LazyValue._value(ScalafixInterface.scala:12)
[error]         at scalafix.internal.sbt.ScalafixInterface$LazyValue.apply(ScalafixInterface.scala:13)
    [error]         at scalafix.sbt.ScalafixPlugin$.scalafixArgs(ScalafixPlugin.scala:96)
[error]         at scalafix.sbt.ScalafixPlugin$.$anonfun$scalafixInputTask$4(ScalafixPlugin.scala:110)
[error]         at sbt.std.FullInstance$.$anonfun$flattenFun$3(TaskMacro.scala:79)
[error]         at scala.Function1.$anonfun$compose$1(Function1.scala:44)
    [error]         at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:40)
    [error]         at sbt.std.Transform$$anon$4.work(System.scala:67)
    [error]         at sbt.Execute.$anonfun$submit$2(Execute.scala:269)
[error]         at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
    [error]         at sbt.Execute.work(Execute.scala:278)
    [error]         at sbt.Execute.$anonfun$submit$1(Execute.scala:269)
[error]         at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:178)
    [error]         at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
    [error]         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    [error]         at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error]         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error]         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error]         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error]         at java.lang.Thread.run(Thread.java:748)
[error] (Compile / scalafix) java.lang.NullPointerException
```

**Comment by soc** [comment]
Closing, because the issue became stale.
Feel free to reopen with new information.
